<?php

namespace Plugin\Summary\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\Summary\Entity\Config;
use Symfony\Bridge\Doctrine\RegistryInterface;
use plugin\Summary\Entity\SummaryConfig;
/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends AbstractRepository
{
    /**
     * ConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, SummaryConfig::class);
    }

    public function newSummaryConfig()
    {
        $SummaryConfig = new \Plugin\Summary\Entity\SummaryConfig();

        return $SummaryConfig;
    }
    /**
     * @param int $id
     *
     * @return SummaryConfig|Config
     */
    public function get($id = 1)
    {
        return $this->find($id);
    }
}
